# Generated by Django 4.2.1 on 2023-05-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('category', models.CharField(blank=True, max_length=60, null=True, verbose_name='категория')),
                ('price_for_buy', models.IntegerField(blank=True, null=True, verbose_name='цена за покупку')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('last_change_date', models.DateTimeField(blank=True, null=True, verbose_name='дата последнего изменения')),
            ],
        ),
    ]
