# Generated by Django 4.2.1 on 2023-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_amount',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
